//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelosControladores.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoOxxoEntities : DbContext
    {
        public ProyectoOxxoEntities()
            : base("name=ProyectoOxxoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacenamiento> Almacenamientoes { get; set; }
        public virtual DbSet<AlmacenamientoBodega> AlmacenamientoBodegas { get; set; }
        public virtual DbSet<AlmacenamientoProducto> AlmacenamientoProductoes { get; set; }
        public virtual DbSet<Asentamiento> Asentamientoes { get; set; }
        public virtual DbSet<Basurero> Basureroes { get; set; }
        public virtual DbSet<BasureroSucursal> BasureroSucursals { get; set; }
        public virtual DbSet<Bodega> Bodegas { get; set; }
        public virtual DbSet<BodegaEquipoLimpieza> BodegaEquipoLimpiezas { get; set; }
        public virtual DbSet<BodegaEstante> BodegaEstantes { get; set; }
        public virtual DbSet<Bolsa> Bolsas { get; set; }
        public virtual DbSet<BolsaSucursal> BolsaSucursals { get; set; }
        public virtual DbSet<Caja> Cajas { get; set; }
        public virtual DbSet<CajaDinero> CajaDineroes { get; set; }
        public virtual DbSet<CajaEmpleado> CajaEmpleadoes { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Contrato> Contratoes { get; set; }
        public virtual DbSet<Dinero> Dineroes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<EmpleadoTurno> EmpleadoTurnoes { get; set; }
        public virtual DbSet<EquipoLimpieza> EquipoLimpiezas { get; set; }
        public virtual DbSet<EquipoSeguridad> EquipoSeguridads { get; set; }
        public virtual DbSet<EquipoSeguridadSucursal> EquipoSeguridadSucursals { get; set; }
        public virtual DbSet<EquipoVigilancia> EquipoVigilancias { get; set; }
        public virtual DbSet<EquipoVigilanciadSucursal> EquipoVigilanciadSucursals { get; set; }
        public virtual DbSet<Estacionamiento> Estacionamientoes { get; set; }
        public virtual DbSet<Estado> Estadoes { get; set; }
        public virtual DbSet<EstadoCivil> EstadoCivils { get; set; }
        public virtual DbSet<Estante> Estantes { get; set; }
        public virtual DbSet<EstanteProducto> EstanteProductoes { get; set; }
        public virtual DbSet<Estudio> Estudios { get; set; }
        public virtual DbSet<Etiqueta> Etiquetas { get; set; }
        public virtual DbSet<EtiquetaProducto> EtiquetaProductoes { get; set; }
        public virtual DbSet<Luce> Luces { get; set; }
        public virtual DbSet<LucesSucursal> LucesSucursals { get; set; }
        public virtual DbSet<Maquina> Maquinas { get; set; }
        public virtual DbSet<MaquinaSucursal> MaquinaSucursals { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<MetodoDePago> MetodoDePagoes { get; set; }
        public virtual DbSet<Municipio> Municipios { get; set; }
        public virtual DbSet<Nacionalidad> Nacionalidads { get; set; }
        public virtual DbSet<Oficina> Oficinas { get; set; }
        public virtual DbSet<PaginaWeb> PaginaWebs { get; set; }
        public virtual DbSet<Pedido> Pedidoes { get; set; }
        public virtual DbSet<PedidoProveedor> PedidoProveedors { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<ProductoSucursal> ProductoSucursals { get; set; }
        public virtual DbSet<Promocion> Promocions { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<ProveedorPedido> ProveedorPedidoes { get; set; }
        public virtual DbSet<ProveedorSucursal> ProveedorSucursals { get; set; }
        public virtual DbSet<Publicidad> Publicidads { get; set; }
        public virtual DbSet<Puesto> Puestoes { get; set; }
        public virtual DbSet<SalidaDeEmergencia> SalidaDeEmergencias { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<ServicioSucursal> ServicioSucursals { get; set; }
        public virtual DbSet<Sucursal> Sucursals { get; set; }
        public virtual DbSet<Tarjeta> Tarjetas { get; set; }
        public virtual DbSet<TipoDeAsentamiento> TipoDeAsentamientoes { get; set; }
        public virtual DbSet<TipoDeMaquina> TipoDeMaquinas { get; set; }
        public virtual DbSet<TipoDeProducto> TipoDeProductoes { get; set; }
        public virtual DbSet<TipoDeProveedor> TipoDeProveedors { get; set; }
        public virtual DbSet<TipoDePublicidad> TipoDePublicidads { get; set; }
        public virtual DbSet<TipoDeServicio> TipoDeServicios { get; set; }
        public virtual DbSet<TipoDeTransaccion> TipoDeTransaccions { get; set; }
        public virtual DbSet<TipoEquipoLimpieza> TipoEquipoLimpiezas { get; set; }
        public virtual DbSet<Transaccion> Transaccions { get; set; }
        public virtual DbSet<Turno> Turnoes { get; set; }
        public virtual DbSet<Uniforme> Uniformes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Zona> Zonas { get; set; }
    }
}
