//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelosControladores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaccion()
        {
            this.Clientes = new HashSet<Cliente>();
        }
    
        public int idTransaccion { get; set; }
        public int monto { get; set; }
        public int idMetodoDePago { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idServicio { get; set; }
        public int idTipoDeTransaccion { get; set; }
        public Nullable<int> numeroReferencia { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> idUsuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public Nullable<int> idUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual MetodoDePago MetodoDePago { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual TipoDeTransaccion TipoDeTransaccion { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
